#!/bin/bash
#
# Software Requirements
#
#  * You must have findent installed.
#      
#      https://sourceforge.net/projects/findent/files/latest/download
#
#
# ---------------------------------------------------------------------------------------------- #


# Check to see if a directory is supplied in the command line
if [ -z $1 ]
then

  # If not present, use the current directory
  echo "No directory supplied"
  echo "Recursively searching current directory for *.f* files"
  dir=./

else

  # Otherwise use the command line argument
  dir=$1

fi

  
timestamp=$( date +%Y_%m_%d_%H_%M )

for file in $(find $dir -type f -name "*.f*");
do

  echo $file


  findent -i2 -RR -C- < $file > temp.txt
  mv temp.txt $file

  # Replace lower case intrinsics with upper case intrinsics
  sed -i -e 's/subroutine/SUBROUTINE/Ig' $file
  sed -i -e 's/function/FUNCTION/Ig' $file
  sed -i -e 's/if/IF/Ig' $file
  sed -i -e 's/then/THEN/Ig' $file
  sed -i -e 's/do/DO/Ig' $file
  sed -i -e 's/contains/CONTAINS/Ig' $file
  sed -i -e 's/implicit none/IMPLICIT NONE/Ig' $file
  sed -i -e 's/case/CASE/Ig' $file
  sed -i -e 's/select/SELECT/Ig' $file
  sed -i -e 's/real/REAL/Ig' $file
  sed -i -e 's/integer/INTEGER/Ig' $file
  sed -i -e 's/logical/LOGICAL/Ig' $file
  sed -i -e 's/common/COMMON/Ig' $file
  sed -i -e 's/use/USE/Ig' $file
  sed -i -e 's/kind/KIND/Ig' $file
  sed -i -e 's/print/PRINT/Ig' $file
  sed -i -e 's/while/WHILE/Ig' $file
  sed -i -e 's/exit/EXIT/Ig' $file
  sed -i -e 's/stop/STOP/Ig' $file
  sed -i -e 's/data/DATA/Ig' $file
  sed -i -e 's/class/CLASS/Ig' $file
  sed -i -e 's/type/TYPE/Ig' $file
  sed -i -e 's/intent/INTENT/Ig' $file
  

done

#n_warnings=$(grep -i "WARNING" prettify.${timestamp}.log | wc -l)
#n_errors=$(grep -i "ERROR" prettify.${timestamp}.log | wc -l)

#echo ${n_warnings}" Warnings"
#echo ${n_errors}" Errors"

#echo "See log file : prettify.${timestamp}.log"




