#!/bin/bash
#
# Software Requirements
#
#  * You must have findent installed.
#      
#      https://sourceforge.net/projects/findent/files/latest/download
#
#
# ---------------------------------------------------------------------------------------------- #


# Check to see if a directory is supplied in the command line
if [ -z $1 ]
then

  # If not present, use the current directory
  echo "No directory supplied"
  echo "Recursively searching current directory for *.f* files"
  dir=./

else

  # Otherwise use the command line argument
  dir=$1

fi

  
timestamp=$( date +%Y_%m_%d_%H_%M )

for file in $(find $dir -type f -name "*.f*");
do

  echo $file

  findent -i2 -RR -C- < $file > temp.txt
  mv temp.txt $file
  

done

#n_warnings=$(grep -i "WARNING" prettify.${timestamp}.log | wc -l)
#n_errors=$(grep -i "ERROR" prettify.${timestamp}.log | wc -l)

#echo ${n_warnings}" Warnings"
#echo ${n_errors}" Errors"

#echo "See log file : prettify.${timestamp}.log"




